### ISSUE TITLE
Member Service

### ISSUE THREAD

**Issue by kcm0147** [KNU-Hackerton-Team-Gongdae9/server#29]
## 기능 구현
- - -

- [x] 내가 쓴 댓글 조회
- [x] 내가 쓴 글 조회
- [X] MemberController반환 형태 통일
- [X] Error Exception 처리
- [X] JWT에서 Member.id 반환 메소드
